import {test} from 'node:test';
import assert from 'node:assert/strict';
import {criarHandler,normalizarServicos,baseValida,vencimentoToken,erroPublico} from '../supabase/functions/cotar-frete/fluxo.mjs';
const produto={id:'p',codigo:'RM-0001',preco:189.9,peso_g:500,largura_cm:25,altura_cm:5,comprimento_cm:30,cep_origem:'30640140',dias_postagem:1};
const respostas=[{id:2,name:'SEDEX',price:'25',custom_price:'23.41',delivery_time:2,custom_delivery_range:{min:1,max:2},company:{name:'Correios'}},{id:1,name:'PAC',price:'18.1',custom_price:'16.20',delivery_time:5,company:{name:'Correios'}},{id:3,name:'Outra',price:1,delivery_time:1,company:{name:'Outra'}}];
function contexto(opcoes={}){const chamadas=[],cache=new Map();const rpc=async(acao,chave,dados)=>{chamadas.push({acao,chave,dados});if(acao==='limite')return {permitido:true};if(acao==='dados')return opcoes.produto??produto;if(acao==='cache_ler')return cache.get(chave);if(acao==='cache_gravar')cache.set(chave,dados);};const handler=criarHandler({rpc,autorizarPublico:async()=>true,autorizarAdmin:async()=>true,token:'TOKEN_SIMULADO_CI',salt:'SALT_SIMULADO_CI',fetcher:async()=>Response.json(respostas),...opcoes});return {handler,chamadas,cache};}
const requisicao=(body={cep:'30140071',codigo:'RM-0001',variacao:null},headers={})=>new Request('https://example.test/functions/v1/cotar-frete',{method:'POST',headers:{apikey:'publica-teste','Content-Type':'application/json','cf-connecting-ip':'192.0.2.1',...headers},body:JSON.stringify(body)});
test('sucesso: banco controla preço/embalagem, kg, seguro, PAC/SEDEX, postagem, header e cache 1h',async()=>{
 let fetches=0,enviado;const ctx=contexto({fetcher:async(url,opts)=>{fetches++;enviado={url,opts};return Response.json(respostas);}});
 const r=await ctx.handler(requisicao()),dados=await r.json();assert.equal(r.status,200);assert.deepEqual(dados.opcoes,[{id:1,servico:'PAC',valor:16.2,prazo_dias:6},{id:2,servico:'SEDEX',valor:23.41,prazo_dias:3}]);
 const pacote=JSON.parse(enviado.opts.body);assert.equal(pacote.products[0].weight,.5);assert.equal(pacote.products[0].insurance_value,189.9);assert.equal(pacote.from.postal_code,'30640140');assert.equal(pacote.services,'1,2');assert.equal(enviado.opts.headers['User-Agent'],'Rose Modas (y.menezessilva@gmail.com)');assert.equal(enviado.opts.headers.Authorization,'Bearer TOKEN_SIMULADO_CI');assert.equal(enviado.url,'https://melhorenvio.com.br/api/v2/me/shipment/calculate');
 assert.ok(Date.parse(dados.expira_em)-Date.now()>3590000);assert.ok(!JSON.stringify(dados).includes('TOKEN_SIMULADO'));assert.ok(!JSON.stringify(ctx.chamadas).includes('192.0.2.1'));assert.ok(!JSON.stringify(dados).includes('Authorization'));
 assert.deepEqual(await(await ctx.handler(requisicao())).json(),dados);assert.equal(fetches,1);
});
test('CEP inválido nunca chama o provedor; preço e dimensões do navegador são rejeitados',async()=>{let n=0;const {handler}=contexto({fetcher:async()=>{n++;return Response.json(respostas);}});for(const cep of ['','1234567','30140-071','abcdefgh']){const r=await handler(requisicao({cep,codigo:'RM-0001'}));assert.equal(r.status,400);assert.equal((await r.json()).erro,'Confira o CEP');}assert.equal((await handler(requisicao({cep:'30140071',codigo:'RM-0001',preco:1}))).status,400);assert.equal(n,0);});
for(const [nome,fetcher,detalhe] of [
 ['erro da API',async()=>new Response('corpo confidencial',{status:500}),'A API de frete está indisponível.'],
 ['token inválido',async()=>new Response('secret',{status:401}),'Token inválido ou expirado.'],
 ['token sem permissão',async()=>new Response('secret',{status:403}),'Token inválido ou expirado.'],
 ['sem resultado',async()=>Response.json([{id:1,error:'indisponível'}]),'Não há PAC ou SEDEX disponível para este CEP.'],
 ['timeout',async(_,opts)=>new Promise((_,reject)=>opts.signal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')))),'A cotação demorou demais. Tente novamente.']
])test(nome+': alternativa pública e erro em português para admin, sem detalhes brutos',async()=>{const {handler}=contexto({fetcher,timeoutMs:5});const cliente=await(await handler(requisicao())).json();assert.deepEqual(cliente,{ok:false,erro:erroPublico});const admin=await(await handler(requisicao(undefined,{Authorization:'Bearer JWT_SIMULADO_CI'}))).json();assert.equal(admin.detalhe,detalhe);assert.ok(!JSON.stringify(admin).includes('secret'));});
test('ausência e expiração do token não bloqueiam a resposta de fallback',async()=>{let n=0;const fetcher=async()=>{n++;return Response.json(respostas);};const token=`a.${Buffer.from(JSON.stringify({exp:1})).toString('base64url')}.c`;for(const tk of ['',token]){const {handler}=contexto({token:tk,fetcher});assert.equal((await(await handler(requisicao())).json()).ok,false);}assert.equal(n,0);assert.equal(vencimentoToken(token),'1970-01-01T00:00:01.000Z');assert.equal(vencimentoToken('opaco'),null);});
test('status do token é exclusivamente admin e revela só presença/data',async()=>{const {handler}=contexto();const req=hdr=>new Request('https://example.test/status',{headers:hdr});assert.equal((await handler(req({apikey:'x'}))).status,403);const r=await(await handler(req({apikey:'x',Authorization:'Bearer JWT_SIMULADO_CI'}))).json();assert.deepEqual(r,{ok:true,configurado:true,expira_em:null});});
test('limite de IP no banco: bloqueia antes da API; credenciais/origens não autorizadas bloqueadas',async()=>{let n=0;const {handler}=contexto({rpc:async()=>({permitido:false}),fetcher:async()=>{n++;return Response.json(respostas);}});assert.equal((await handler(requisicao())).status,429);assert.equal(n,0);assert.equal((await contexto({autorizarPublico:async()=>false}).handler(requisicao())).status,401);assert.equal((await contexto().handler(requisicao(undefined,{Origin:'https://fraude.test'}))).status,403);const r=await contexto().handler(new Request('https://example.test',{method:'OPTIONS',headers:{Origin:'https://homolog.rosemenezesmodas.com.br'}}));assert.equal(r.status,204);assert.equal(r.headers.get('Access-Control-Allow-Origin'),'https://homolog.rosemenezesmodas.com.br');});
test('base permite somente domínios do Melhor Envio; respostas inválidas não prometem preço/prazo',()=>{assert.equal(baseValida('https://sandbox.melhorenvio.com.br'),'https://sandbox.melhorenvio.com.br/api/v2');for(const url of ['http://melhorenvio.com.br','https://evil.test','https://melhorenvio.com.br@evil.test','https://melhorenvio.com.br/checkout'])assert.throws(()=>baseValida(url));assert.deepEqual(normalizarServicos([{id:1,price:'NaN',delivery_time:4,company:{name:'Correios'}},{id:2,price:10,company:{name:'Correios'}},{id:1,price:0,delivery_time:4,company:{name:'Correios'}}],1),[]);});

test('valor adicional zero preserva preços; acréscimo em reais usa centavos e invalida cache',async()=>{
 const p={...produto,valor_adicional:0};let fetches=0,enviado;
 const ctx=contexto({produto:p,fetcher:async(_url,opts)=>{fetches++;enviado=JSON.parse(opts.body);return Response.json(respostas);}});
 const primeira=await(await ctx.handler(requisicao())).json();assert.deepEqual(primeira.opcoes,normalizarServicos(respostas,1));
 await ctx.handler(requisicao());assert.equal(fetches,1);
 p.valor_adicional=3.5;const segunda=await(await ctx.handler(requisicao())).json();assert.deepEqual(segunda.opcoes,[{id:1,servico:'PAC',valor:19.7,prazo_dias:6},{id:2,servico:'SEDEX',valor:26.91,prazo_dias:3}]);assert.equal(fetches,2);
 assert.equal(enviado.products[0].insurance_value,189.9);assert.equal(enviado.products[0].quantity,1);assert.ok(!('valor_adicional' in enviado));
 assert.equal((await ctx.handler(requisicao({cep:'30140071',codigo:'RM-0001',valor_adicional:0}))).status,400);
 assert.deepEqual(normalizarServicos([respostas[0]],1,3.5),[{id:2,servico:'SEDEX',valor:26.91,prazo_dias:3}]);
});
test('adicional negativo, não numérico, acima do limite ou com fração de centavo não chega à API',async()=>{
 let n=0;for(const valor_adicional of [-1,'abc',10000.01,1.001]){const {handler}=contexto({produto:{...produto,valor_adicional},fetcher:async()=>{n++;return Response.json(respostas);}});assert.equal((await(await handler(requisicao())).json()).ok,false);}assert.equal(n,0);
});
