import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'vite';
import react from '@vitejs/plugin-react';
import {JSDOM} from 'jsdom';
let codigoBundle;
async function preparar(){
 if(!codigoBundle){const mock={name:'cotacao-teste-apenas-ci',transform(code,id){if(id.endsWith('/src/catalogo.ts'))return code.replace('export function urlDaMidia(', 'function urlDaMidiaReal(')+'\nexport function urlDaMidia(c){return `https://example.test/${c}`;}';if(!id.endsWith('/src/frete.ts'))return;return code.replace('export async function cotarFrete(', 'async function cotarFreteReal(')+'\nexport async function cotarFrete(...args){return globalThis.__cotacao(...args);}';}};const r=await build({configFile:false,envFile:false,logLevel:'silent',plugins:[mock,react()],define:{'import.meta.env':JSON.stringify({VITE_APP_ENV:'development',VITE_SUPABASE_URL:'http://127.0.0.1:54321',VITE_SUPABASE_PUBLISHABLE_KEY:'sb_publishable_CI_TEST'}),'process.env.NODE_ENV':'"development"'},build:{write:false,minify:false,lib:{entry:'tests/frete-harness.tsx',name:'FreteTeste',formats:['iife']}}});codigoBundle=(Array.isArray(r)?r[0]:r).output.find(x=>x.type==='chunk').code;}
 const dom=new JSDOM('<div id="teste"></div>',{url:'https://example.test/#/loja/produto/peca',runScripts:'outside-only',beforeParse(w){w.MessageChannel=class{port1={onmessage:null};port2={postMessage:()=>setTimeout(()=>this.port1.onmessage?.(),0)};};w.AbortController=AbortController;w.AbortSignal=AbortSignal;}});dom.window.eval(codigoBundle);return {dom,d:dom.window.document,ui:dom.window.testeFrete};
}
const resposta=(cep='30140071')=>({ok:true,cep,codigo:'RM-0001',opcoes:[{id:1,servico:'PAC',valor:16.2,prazo_dias:6},{id:2,servico:'SEDEX',valor:23.41,prazo_dias:3}],expira_em:new Date(Date.now()+3600000).toISOString()});
async function preencher(ctx,valor){await ctx.ui.act(()=>{const el=ctx.d.querySelector('input');Object.getOwnPropertyDescriptor(ctx.dom.window.HTMLInputElement.prototype,'value').set.call(el,valor);el.dispatchEvent(new ctx.dom.window.Event('input',{bubbles:true}));});}
async function calcular(ctx){await ctx.ui.act(async()=>{ctx.d.querySelector('form').dispatchEvent(new ctx.dom.window.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,10));});}
test('CEP mascarado e lembrado, opções ordenadas, seleção opcional e descarte de cotação antiga',async()=>{const ctx=await preparar();const {dom,d,ui}=ctx;let widget,selecao,cotacoes=0;const props={codigo:'RM-0001',variacao:null,escolheu:f=>selecao=f,consultar:()=>{},cotar:async cep=>{cotacoes++;return resposta(cep.replace(/\D/g,''));}};
 try{await ui.act(()=>widget=ui.montarCalculadora(props));assert.equal(d.querySelector('input').inputMode,'numeric');await preencher(ctx,'30140071');assert.equal(d.querySelector('input').value,'30140-071');assert.equal(dom.window.localStorage.getItem('rosemodas:cep'),'30140071');await calcular(ctx);assert.equal(selecao,null);assert.match(d.querySelector('fieldset').textContent,/PAC · R\$.*16,20.*6 dias úteis.*SEDEX/);await ui.act(()=>d.querySelector('input[type=radio]').click());assert.equal(selecao.servico,'PAC');assert.match(ui.trechoFreteWhatsApp(selecao),/CEP 30140-071 · PAC/);
 await preencher(ctx,'01310100');assert.equal(selecao,null);assert.equal(d.querySelector('fieldset'),null);await calcular(ctx);await ui.act(()=>d.querySelector('input[type=radio]').click());await ui.act(()=>widget.alterar({...props,variacao:'outra'}));assert.equal(selecao,null);assert.equal(d.querySelector('fieldset'),null);assert.equal(d.querySelector('input').value,'01310-100');assert.equal(cotacoes,2);
 await ui.act(()=>widget.sair());await ui.act(()=>widget=ui.montarCalculadora({...props,codigo:'RM-0002'}));assert.equal(d.querySelector('input').value,'01310-100');await preencher(ctx,'123');await calcular(ctx);assert.equal(d.querySelector('[role=alert]').textContent,'Confira o CEP');assert.equal(cotacoes,2);assert.equal(ui.trechoFreteWhatsApp({...selecao,cep:'01310100',expira_em:'2000-01-01'}),'');
 }finally{await ui.act(()=>widget?.sair());dom.window.close();}
});
test('compra e encomenda sempre ativas: mensagem sem frete, com frete escolhido e após erro da API',async()=>{
 for(const esgotada of [false,true]){const ctx=await preparar();const {dom,d,ui}=ctx;let sair,msg;const p={id:'p',codigo:'RM-0001',slug:'peca',nome:'Vestido CI',categoria_id:null,colecao_id:null,preco:199,preco_promocional:null,selo:null,midias:[{tipo:'foto',caminho_storage:'foto.webp',principal:true,ordem:0,alt_texto:'Vestido'}]};const saldos=[{variacao_id:'00000000-0000-4000-8000-000000000001',produto_id:'p',cor:'',tamanho:'G',disponivel:esgotada?0:1}];const catalogo={saldos,produtos:[p],categorias:[],colecoes:[],medidas:[]};dom.window.__cotacao=async()=>resposta();
 try{await ui.act(()=>sair=ui.montarPagina({produto:p,catalogo,aviso:()=>{},whatsapp:s=>msg=s,relacionados:null,homologacao:true}));assert.equal(d.querySelector('.buy button').disabled,false);await ui.act(()=>d.querySelector('.buy button').click());assert.ok(!msg.includes('Frete informativo'));assert.match(msg,/RM-0001/);assert.match(msg,/G/);await preencher(ctx,'30140071');await calcular(ctx);await ui.act(()=>d.querySelector('.buy button').click());assert.ok(!msg.includes('Frete informativo'),'cotação sem seleção não entra');await ui.act(()=>d.querySelector('input[type=radio]').click());await ui.act(()=>d.querySelector('.buy button').click());assert.match(msg,/Frete informativo: CEP 30140-071 · PAC/);assert.match(msg,/até 6 dias úteis/);assert.equal(d.querySelector('.buy button').textContent,esgotada?'Encomendar pelo WhatsApp':'Comprar pelo WhatsApp');
 dom.window.__cotacao=async()=>{throw new Error('Não conseguimos calcular agora. Consulte o frete pelo WhatsApp');};await preencher(ctx,'69005010');await calcular(ctx);assert.match(d.querySelector('[role=alert]').textContent,/Não conseguimos calcular agora/);await ui.act(()=>d.querySelector('.buy button').click());assert.ok(!msg.includes('Frete informativo'));assert.equal(d.querySelector('.buy button').disabled,false);assert.equal(d.querySelector('.calculadora-frete>button').textContent,'Consultar frete pelo WhatsApp');
 }finally{await ui.act(()=>sair?.());dom.window.close();}}
});
